import { Link } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import {
  Award,
  Upload,
  MousePointer,
  Palette,
  Download,
  FileSpreadsheet,
  Zap,
  Shield,
  Users,
} from "lucide-react";

/* ----------------------------------
   DATA
---------------------------------- */
const features = [
  { icon: Upload, title: "Upload Template", description: "Bring your own certificate design." },
  { icon: FileSpreadsheet, title: "Import Names", description: "Bulk upload recipients via CSV." },
  { icon: MousePointer, title: "Position Text", description: "Precisely place names visually." },
  { icon: Palette, title: "Customize Style", description: "Fonts, colors, and sizing control." },
  { icon: Zap, title: "Generate", description: "Backend generates at scale instantly." },
  { icon: Download, title: "Download ZIP", description: "All certificates packaged together." },
];

const stats = [
  { value: "50K+", label: "Certificates Generated" },
  { value: "2K+", label: "Active Teams" },
  { value: "99.9%", label: "Service Uptime" },
  { value: "<3s", label: "Avg Generation Time" },
];

/* ----------------------------------
   PAGE
---------------------------------- */
export default function Index() {
  return (
    <Layout>
      {/* =====================================================
         HERO — CERTIFICATE AS PRODUCT
      ===================================================== */}
      <section className="relative py-28 bg-background">
        <div className="container flex justify-center">
          <div className="relative w-full max-w-6xl glass-strong lift-hover px-16 py-20">

            {/* Border framing */}
            <div className="absolute inset-4 border border-primary/30 pointer-events-none" />
            <div className="absolute inset-7 border border-primary/10 pointer-events-none" />

            {/* Header */}
            <div className="text-center mb-10">
              <span className="text-xs uppercase tracking-widest text-muted-foreground">
                Certificate Automation Platform
              </span>
            </div>

            <h1 className="text-center text-4xl md:text-5xl font-semibold tracking-wide mb-6">
              This Certificate is Generated by
            </h1>

            <div className="text-center mb-10">
              <span className="text-6xl md:text-7xl font-extrabold text-primary">
                CertifyHQ
              </span>
            </div>

            <p className="max-w-3xl mx-auto text-center text-lg text-muted-foreground mb-16">
              A professional platform to generate high-volume certificates using your
              own templates, structured data, and a scalable backend.
            </p>

            {/* Seal Row */}
            <div className="flex items-center justify-between mb-16 px-12">
              <div>
                <p className="text-xs uppercase text-muted-foreground">Authorized System</p>
                <p className="font-medium">CertifyHQ Engine</p>
              </div>

              <div className="h-20 w-20 rounded-full border border-primary/40
                              flex items-center justify-center font-semibold text-primary">
                HQ
              </div>

              <div className="text-right">
                <p className="text-xs uppercase text-muted-foreground">Execution</p>
                <p className="font-medium">Automated</p>
              </div>
            </div>

            {/* Actions */}
            <div className="flex justify-center gap-6">
              <Link to="/generator">
                <Button className="btn-primary px-10 py-3 text-base">
                  Start Generating
                </Button>
              </Link>
              <Link to="/templates">
                <Button className="btn-outline px-10 py-3 text-base">
                  View Templates
                </Button>
              </Link>
            </div>

          </div>
        </div>
      </section>

      {/* =====================================================
         STATS — SYSTEM METRICS
      ===================================================== */}
      <section className="border-y border-border bg-muted/30">
        <div className="container py-14">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-10">
            {stats.map((s) => (
              <div key={s.label} className="text-center">
                <div className="text-3xl font-semibold text-primary">{s.value}</div>
                <div className="text-sm text-muted-foreground mt-1">{s.label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =====================================================
         WORKFLOW
      ===================================================== */}
      <section className="py-24">
        <div className="container">
          <div className="max-w-3xl mb-16">
            <h2 className="text-3xl font-semibold mb-4">
              Built for Scale
            </h2>
            <p className="text-muted-foreground">
              CertifyHQ is designed as an operational tool — predictable, fast, and reliable.
            </p>
          </div>

          <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
            {features.map((f, i) => (
              <div key={f.title} className="card-glass p-6 lift-hover">
                <div className="flex items-start gap-4">
                  <div className="h-10 w-10 rounded-md bg-primary/15
                                  flex items-center justify-center">
                    <f.icon className="h-5 w-5 text-primary" />
                  </div>
                  <div>
                    <p className="text-xs text-muted-foreground mb-1">Step {i + 1}</p>
                    <h3 className="font-medium mb-1">{f.title}</h3>
                    <p className="text-sm text-muted-foreground">{f.description}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* =====================================================
         TRUST
      ===================================================== */}
      <section className="py-24 border-y border-border bg-muted/30">
        <div className="container">
          <div className="grid md:grid-cols-3 gap-10 text-center">
            <Trust icon={Shield} title="Secure by Design" text="Data processed with isolation and encryption." />
            <Trust icon={Zap} title="High Performance" text="Optimized for bulk workloads." />
            <Trust icon={Users} title="Team Ready" text="Used by educators, HR, and events." />
          </div>
        </div>
      </section>

      {/* =====================================================
         CTA
      ===================================================== */}
      <section className="py-24">
        <div className="container text-center">
          <h2 className="text-3xl font-semibold mb-4">
            Ready to automate certificates?
          </h2>
          <p className="text-muted-foreground mb-8">
            Start using CertifyHQ today.
          </p>
          <Link to="/generator">
            <Button className="btn-primary px-12 py-3 text-base">
              Launch Generator
            </Button>
          </Link>
        </div>
      </section>
    </Layout>
  );
}

/* ----------------------------------
   TRUST CARD
---------------------------------- */
function Trust({ icon: Icon, title, text }: any) {
  return (
    <div className="card-glass p-8">
      <div className="h-12 w-12 mx-auto mb-4 bg-primary/15
                      flex items-center justify-center rounded-md">
        <Icon className="h-6 w-6 text-primary" />
      </div>
      <h3 className="font-medium mb-2">{title}</h3>
      <p className="text-sm text-muted-foreground">{text}</p>
    </div>
  );
}
